customer.params.p1=11
customer.params.p2=22


spring.datasource.url=jdbc:h2:mem:customers-db
#base à renseigner: jdbc:h2:mem:customers-db
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# http://localhost:8081/h2-console
spring.cloud.discovery.enabled=true

# spring.cloud.config.enabled=false on met à true...
spring.cloud.config.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.data.rest.base-path=/api


# Correction des liens HATEOAS pour passer par la Gateway
# server.forward-headers-strategy=framework
# Indispensable pour que les liens HATEOAS passent par la Gateway
# server.forward-headers-strategy=framework

management.endpoints.web.exposure.include=refresh
