
spring.datasource.url=jdbc:h2:mem:products-db
#base à renseigner: jdbc:h2:mem:products-db
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# http://localhost:8082/h2-console
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.data.rest.base-path=/api

#all actuator possibilities
management.endpoints.web.exposure.include=*

# Correction des liens HATEOAS pour passer par la Gateway
#server.forward-headers-strategy=framework