spring.application.name=inventory-service
server.port=8082
spring.datasource.url=jdbc:h2:mem:products-db
#base à renseigner: jdbc:h2:mem:products-db
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# http://localhost:8082/h2-console
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false

#all actuator possibilities
management.endpoints.web.exposure.include=*