spring.application.name=gateway-service
server.port=8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Nouvelles clés Gateway 4.x
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Préserve le header Host (localhost:8888) pour que les liens HATEOAS passent par la Gateway
spring.cloud.gateway.server.webflux.default-filters[0]=PreserveHostHeader